### ISSUE TITLE
A place for track specific metadata in the .yml files

### ISSUE THREAD

**Issue by pminten** [exercism/x-common#72]
If you look at the ideas that have been floating around regarding exercise quality a fair lot of them involve classifying exercises in whatever kind of way. While there's no clear idea yet about how to best go about that I'd like to propose using the .yml files for track specific metadata that could be processed by program (for example to generate overviews).

The technical mechanism I'm imagining would look somewhat like this:

``` yaml
blurb: "Write a program that, given a number, can find the sum of all the multiples of 3 or 5 up to but not including that number."
source: "A variation on Problem 1 at Project Euler"
source_url: "http://projecteuler.net/problem=1"
common:
  type: practice
  topics: [loops]
go:
  topics: [loops, "anonymous functions"]
```

The new bits are the `common` and `go` mappings. The idea is that `common` contains attributes for all tracks which can be overridden on a track specific basis, which `go` does for the `topics` attribute.

If I understand x-api/lib/x-api/readme.rb correctly adding extra entries to the top level mapping shouldn't cause any problems so any change based on this proposal should be backwards compatible.
